### ISSUE TITLE
Inconsistent lock periods

### ISSUE THREAD

**Issue by KristiforMilchev** [KeysFortress/KeyFortress#68]
Due to the timer not being canceled after it expires, it starts a new thread running the count before the user enters the password, sometimes leading to a double lock.

**Comment by KristiforMilchev** [comment]
The builds is up and ready for testing whenever you have time.

**Comment by Tyler-Kuhn** [comment]
@KristiforMilchev - tested

### **TC4** - **Verify Application locks in the same time period consistently.**

**FAILED**

**Environment:** Android Studio
                            Pixel Pro 7
                            Android 14

**Steps:**

1.     Launch the Key Fortress application on Mobile 
2.     Time how long it takes for application to lock.
3.     Unlock application with password.
4.     Time how long it takes for application to lock.
5.     Compare times

**Expected:**  The times should be consistent.

**Actual:**  The applications only locks if you tap the copy button and wait 30 sec, then does not lock again when unlocked without leaving the app.


First Lock
https://github.com/KeysFortress/KeyFortress/assets/143207371/aac6ae0d-7cd6-4011-a2e4-82de762bfb22

Second Lock (Bug: doesn't lock)
https://github.com/KeysFortress/KeyFortress/assets/143207371/25dad53b-3fbd-480b-8840-3511c3083fea

**Comment by KristiforMilchev** [comment]
This not now ready for testing 
https://drive.google.com/file/d/1rg7klXuiHiPZIxBH43mW-u1-9UxvxSbI/view?usp=sharing

**Comment by Tyler-Kuhn** [comment]
**Retested - Passed**

### **TC4 - Verify Application locks in the same time period consistently.**
**Environment:**

- Android Studio
- Pixel 7 Pro
- Android 14

**Steps:**
1. Launch the Key Fortress application on Mobile
2. Wait 30 sec for the application to lock
3. Unlock application
4. Wait 30 sec for application to lock
5. Compare Results

**Expected Result:**
The times are consistent.

**Actual Result:**
The times are consistent.
