### ISSUE TITLE
Copy button must be clicked for the auto lock timer to start.

### ISSUE THREAD

**Issue by KristiforMilchev** [KeysFortress/KeyFortress#70]

**Comment by KristiforMilchev** [comment]
Ready for testing as well
https://drive.google.com/file/d/1rg7klXuiHiPZIxBH43mW-u1-9UxvxSbI/view?usp=sharing

**Comment by Tyler-Kuhn** [comment]
**Retested** - **Passed**

### **TC3 - Verify Application locks without being interacted with.**

**Environment:**
     Android Studio
     Pixel 7 Pro
     Android 14

**Steps:**
     1. Launch the Key Fortress application on Mobile
     2. Wait 30 sec for the application to lock

**Expected Result:** 
The Application locks and requires password to open.

**Actual Result:**
The Application locks and requires password to open.
