### ISSUE TITLE
Saves multiple of the same password if you press the save button more than once before confirmation window pops up.

### ISSUE THREAD

**Issue by Tyler-Kuhn** [KeysFortress/KeyFortress#90]

**Comment by Tyler-Kuhn** [comment]
### **TC12 - When Password is saved it only saves one time. - FAILED**

**Environment:** Android Studio
                      Pixel 7
                      Android 14

**Steps:**

1. Launch the Key Fortress application on Phone.
2. Unlock app with set password.
3. Press the "Generate Password" button to open the password generation window.
4. Enter a Name and Email.
5. Click "Save" as many time as you can before the Confirmation window pops up.

**Expected Result:**
 The password should only save once.

**Actual Result:**
The password saves as many times as you can hit the save button.

**Recording**
https://github.com/KeysFortress/KeyFortress/assets/143207371/b27e764e-24f4-4868-9ccc-c6642ffdf923

**Comment by KristiforMilchev** [comment]
Patched with PR  https://github.com/KeysFortress/KF_Components/pull/21

**Comment by Tyler-Kuhn** [comment]
TC12 - When Password is saved it only saves one time. - PASSED
Environment: Android Studio
Pixel 7
Android 14

Steps:

Launch the Key Fortress application on Phone.
Unlock app with set password.
Press the "Generate Password" button to open the password generation window.
Enter a Name and Email.
Click "Save" as many time as you can before the Confirmation window pops up.
Expected Result:
The password should only save once.

Actual Result:
The password should only save once.
